- hosts: terraform-ansible
  tasks:
  - name: instalar python3 e virtualenv
    apt:
      pkg:
        - python3
        - virtualenv
      update_cache: true
    become: true
  - name: instalar dependencias com pip
    pip:
      virtualenv: /home/ubuntu/venv
      name: 
        - django
        - djangorestframework
  - name: criar arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Criando arquivos na VM com Terraform usando Ansible</h1>
  - name: criar servidor
    shell: "nohup busybox httpd -f -p 8080 &"